//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahaflarPazari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int AdresId { get; set; }
        public int KullaniciId { get; set; }
        public string AdresAdi { get; set; }
        public string Sehir { get; set; }
        public string Ilce { get; set; }
        public string Mahalle { get; set; }
        public string PostaKodu { get; set; }
        public string AdresAlani { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }

        public override string ToString()
        {
            return $"Kullanıcı ID: {KullaniciId}\nAdres Adı: {AdresAdi}\nŞehir: {Sehir}\nİlçe: {Ilce}\nMahalle: {Mahalle}\nPosta Kodu: {PostaKodu}\nAdres Alanı: {AdresAlani}";
        }
    }
}
