//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahaflarPazari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstekListesi
    {
        public int KullaniciId { get; set; }
        public Nullable<int> KitapId { get; set; }
        public int ListeId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kitap Kitap { get; set; }
    }
}
