//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahaflarPazari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kitap()
        {
            this.IstekListesi = new HashSet<IstekListesi>();
            this.KitapResimleri = new HashSet<KitapResimleri>();
            this.Siparisler = new HashSet<Siparisler>();
            this.AlisverisSepeti = new HashSet<AlisverisSepeti>();
            this.Sikayet = new HashSet<Sikayet>();
        }
    
        public int KitapId { get; set; }
        public int SaticiId { get; set; }
        public int KategoriId { get; set; }
        public int Fiyat { get; set; }
        public string KitapAdi { get; set; }
        public string Detay { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
        public Nullable<int> YayineviId { get; set; }
        public string Yazar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstekListesi> IstekListesi { get; set; }
        public virtual KitapKategorileri KitapKategorileri { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Yayinevi Yayinevi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitapResimleri> KitapResimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siparisler> Siparisler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlisverisSepeti> AlisverisSepeti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sikayet> Sikayet { get; set; }
    }
}
