//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahaflarPazari.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SahaflarPazariEntities : DbContext
    {
        public SahaflarPazariEntities()
            : base("name=SahaflarPazariEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KitapKategorileri> KitapKategorileri { get; set; }
        public virtual DbSet<KitapResimleri> KitapResimleri { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciBilgileri> KullaniciBilgileri { get; set; }
        public virtual DbSet<IstekListesi> IstekListesi { get; set; }
        public virtual DbSet<Yayinevi> Yayinevi { get; set; }
        public virtual DbSet<Kitap> Kitap { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<AlisverisSepeti> AlisverisSepeti { get; set; }
        public virtual DbSet<Sikayet> Sikayet { get; set; }
    }
}
