//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SahaflarPazari.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisId { get; set; }
        public int KullaniciId { get; set; }
        public int KitapId { get; set; }
        public string Adres { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public string SiparisDurumu { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
